import fs from 'fs'
import path from 'path'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import matter from 'gray-matter'
import Post from '../components/Post'
import { sortByDate } from '../utils'
export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nirmal Krishna</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {posts.map((post, i) => {
        return <Post key={i} post={post} />
      })}
    </div>
  )
}

export async function getStaticProps() {
  //get files from the posts dir,
  const files = fs.readdirSync(path.join('posts'))

  //get slug and front matter from posts
  const posts = files.map((file) => {
    // slug
    const slug = file.replace('.md', '')

    // get front matter
    const md = fs.readFileSync(path.join('posts', file), 'utf-8')
    const { data: fm } = matter(md)
    return {
      slug,
      fm,
    }
  })

  return {
    props: {
      posts: posts.sort(sortByDate),
    },
  }
}
